### ISSUE TITLE
Installing on Windows 10 VS Code not wokring

### ISSUE THREAD

**Issue by dignin** [bpmn-io/vs-code-bpmn-io#96]
I installed the package from the market place.

It shows as installed and enabled but is not allowing me to open BPMN editor from menu or command pallette.

I uninstalled, downloadde and reinstalled it on the command line

C:\Users\Shawn\AppData\Local\Programs\Microsoft VS Code\bin>code --install-extension c:\Users\Shawn\Downloads\vs-code-bpmn-io-0.12.0.vsix
Installing extensions...
(node:6720) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
Extension 'vs-code-bpmn-io-0.12.0.vsix' was successfully installed.

I restarted the VS code, opened a file with .bpmn extension created on demo.bpmn.io and get only XML.

code --list-extensions --show-versions
abusaidm.html-snippets@0.2.1
adpyke.vscode-sql-formatter@1.4.4
analytic-signal.preview-pdf@0.0.3
bpmn-io.vs-code-bpmn-io@0.12.0
DavidAnson.vscode-markdownlint@0.40.4
dbaeumer.vscode-eslint@2.1.20
deltaxml.xslt-xpath@0.2.7
DigitalBrainstem.javascript-ejs-support@1.3.1
esbenp.prettier-vscode@6.4.0
fabiospampinato.vscode-diff@1.4.1
formulahendry.code-runner@0.11.3
GrapeCity.gc-excelviewer@3.0.41
hex-ci.stylelint-plus@0.53.4
MrAwesomeRocks.lipsum-generator@1.2.1
ms-azuretools.vscode-docker@1.12.1
ms-python.python@2021.5.829140558
ms-python.vscode-pylance@2021.5.1
ms-toolsai.jupyter@2021.6.811652604
ms-vscode-remote.remote-wsl@0.56.1
ms-vscode.atom-keybindings@3.0.9
ms-vscode.powershell@2021.2.2
naumovs.color-highlight@2.3.0
streetsidesoftware.code-spell-checker@1.10.2
streetsidesoftware.code-spell-checker-german@0.1.8
techer.open-in-browser@2.0.0
VisualStudioExptTeam.vscodeintellicode@1.2.13

C:\Users\Shawn\AppData\Local\Programs\Microsoft VS Code\bin>code --version
1.56.0
cfa2e218100323074ac1948c885448fdf4de2a7f
x64

Windows 10

![image](https://user-images.githubusercontent.com/891283/117806043-0f64d800-b25a-11eb-82e7-b438eb57d5dc.png)

**Comment by dignin** [comment]
so, i disabled more; i will research which one it may have been.

Now I got 

![image](https://user-images.githubusercontent.com/891283/117852022-35ed3800-b287-11eb-8f0e-cb520f52032f.png)

Not sure how to save the files now. If you can give me a hint, I will work on identifying the offending module which prevented installation.

**Comment by dignin** [comment]
So, it appears this package deltaxml.xslt-xpath causes the issue. If it's enabled, the button to open bpmn-io is gone.


Now if I just know how to save.......

**Comment by pinussilvestrus** [comment]
The package is also registering [its language support for `.bpmn` files.](https://github.com/DeltaXML/vscode-xslt-tokenizer/blob/master/package.json#L705) as XML, which is overriding ours.

This seems to be an [occurring problem](https://stackoverflow.com/questions/56121280/competing-language-configurations-in-vscode-extensions). I'm not sure how much we can do from our side. It seems like registering lots of file types as XML is not the correct way to do it, but rather be explicit on this. So quoting [from this thread
](https://stackoverflow.com/a/55076005)

> This won't replace the previous registration of the markdown language, instead, it will be merged with it.

it should be something like that (and what `vs-code-bpmn-io` is doing)

```json
"languages": [
  {
    "id": "bpmn",
     "aliases": [
       "BPMN",
       "bpmn"
    ],
    "extensions": [
      ".bpmn2",
      ".bpmn",
      ".bpmn20.xml"
    ]
  }
]
```

I'd recommend opening an issue on the [`vscode-xslt-tokenizer`](https://github.com/DeltaXML/vscode-xslt-tokenizer) to ask whether they could be more sensitive when registering languages. Otherwise, it will override all other plugins with their basic XML configuration.

I'll close this issue until we see an action need from our side.

**Comment by dignin** [comment]
backlink to issue by vscode-xslt-tokenizer

https://github.com/DeltaXML/vscode-xslt-tokenizer/issues/62#issue-889799490


Just for the record.

**Comment by pinussilvestrus** [comment]
Thanks a lot!

**Comment by pgfearo** [comment]
The latest v0.2.8 update of the extension [XSLT/XPath for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=deltaxml.xslt-xpath) hopefully fixes the compatibility issue. See issue: [vscode-xslt-tokenizer#62](https://github.com/DeltaXML/vscode-xslt-tokenizer/issues/62)
